// <auto-generated />
namespace DynamicFilter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v12_MoreFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v12_MoreFields));
        
        string IMigrationMetadata.Id
        {
            get { return "202005252031171_v12_MoreFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
